#!/usr/bin/env bash
#!/usr/bin/env bash

selected=$(find ~/ ~/personal ~/work_repos -mindepth 1 -maxdepth 1 -type d | fzf)

selected_name=$(basename "$selected" | tr . _)

# Check if the TMUX environment variable is set (inside a tmux session)
if [ -n "$TMUX" ]; then
    # Check if the session already exists within the current tmux session
    if ! tmux has-session -t=$selected_name 2> /dev/null; then
        # The session doesn't exist, create it
        tmux new-session -s $selected_name -c $selected -d
    fi

    # Switch to the session within the current tmux session
    tmux switch-client -t $selected_name

else
    # You are not in a tmux session, check if the session exists
    if tmux has-session -t=$selected_name 2> /dev/null; then
        # The session exists, attach to it
        tmux attach-session -t $selected_name
    else
        # The session doesn't exist, create a new session
        tmux new-session -s $selected_name -c $selected -d
        tmux attach-session -t $selected_name
    fi
fi
