#!/usr/bin/env bash
#
#
rm ~/.zshrc
if [[ -z $STOW_FOLDERS ]]; then
    STOW_FOLDERS="i3,nvim,tmux,zsh,bash"
fi

set -f 
array=(${STOW_FOLDERS//,/ })

for folder in "${array[@]}"
do
    echo "stow $folder"
    stow -D $folder
    stow $folder
done
